### PR TITLE
Unit Test For API

### PR DESCRIPTION
**Pull request by vr-varad**

### CODE REVIEW

**Comment by vr-varad** [comment]
I only did it for the controller and will continue committing for other services. @AkisKourouklis

**Comment by AkisKourouklis** [comment]
@vr-varad I've published the branched you have created and did some small changes on your code. Please pull the changes before you continue.

https://github.com/vanguardvirtual/repo-ranger/tree/api/test

**Comment by vr-varad** [comment]
Ok Thanks @AkisKourouklis

**Comment by AkisKourouklis** [comment]
@vr-varad No you don't have for sockets or Twitter. I will think about it maybe we do it in the future

**Comment by vr-varad** [comment]
Then it's done. Could u please review it when u are free.

**Comment by vr-varad** [comment]
Then it's done. Could u please review it when u are free.
@AkisKourouklis

**Comment by AkisKourouklis** [comment]
@vr-varad Thank you for your contribution the changes have been merged

**Pull request merged**
